const malla = [
  // -------- Educación Media en Inglés (1º año) --------
  { id: "fon1", ramo: "Inglés Oral: Pronunciación, Entonación y Expresión I", semestre: 1, prereq: [] },
  { id: "com1", ramo: "Comunicación Oral y Escrita I", semestre: 1, prereq: [] },
  { id: "rol", ramo: "El Rol del Profesor en Contexto Educativo", semestre: 1, prereq: [] },
  { id: "obs1", ramo: "Práctica de Observación I", semestre: 1, prereq: [] },
  { id: "amb1", ramo: "Creación de un Ambiente en Inglés para Principiantes", semestre: 1, prereq: [] },
  { id: "recur", ramo: "Creación y Búsqueda de Recursos para el Aula", semestre: 1, prereq: [] },
  { id: "fon2", ramo: "Inglés Oral: Pronunciación, Entonación y Expresión II", semestre: 2, prereq: ["fon1"] },
  { id: "com2", ramo: "Comunicación Oral y Escrita II", semestre: 2, prereq: ["com1"] },
  { id: "obs2", ramo: "Práctica de Observación II", semestre: 2, prereq: ["obs1"] },
  { id: "teatro", ramo: "Aprendizaje del Inglés a través de Teatro Creativo", semestre: 2, prereq: [] },
  { id: "estudios1", ramo: "Aprendizaje del Inglés a través de Estudios Culturales I", semestre: 2, prereq: [] },
  { id: "tec1", ramo: "Uso de la Tecnología para la Comunicación Global I", semestre: 2, prereq: [] },

  // -------- Cambio de carrera --------
  { id: "cambio-carrera", esCambio: true },

  // -------- Educación Parvularia (desde 2º año) --------
  { id: "leng1", ramo: "Lenguaje y Comunicación en Educación Parvularia I", semestre: 3, prereq: [] },
  { id: "mat1", ramo: "Matemática en Educación Parvularia I", semestre: 3, prereq: [] },
  { id: "lite", ramo: "Literatura y Canciones en Inglés para Párvulos", semestre: 3, prereq: ["fon2"] },
  { id: "salud", ramo: "Salud y Nutrición del Párvulo", semestre: 3, prereq: [] },
  { id: "facileng", ramo: "Facilitación de la Adquisición de la Lengua Extranjera en Niños", semestre: 3, prereq: ["fon2"] },
  { id: "leng2", ramo: "Lenguaje y Comunicación en Educación Parvularia II", semestre: 4, prereq: ["leng1"] },
  { id: "mat2", ramo: "Matemática en Educación Parvularia II", semestre: 4, prereq: ["mat1"] },
  { id: "eval", ramo: "Evaluación en Educación Parvularia", semestre: 4, prereq: ["leng1"] },
  { id: "csoc", ramo: "Ciencias Sociales en Educación Parvularia", semestre: 4, prereq: [] },
  { id: "diflen", ramo: "Dificultades en el Desarrollo del Lenguaje en el Nivel de Educación Parvularia", semestre: 4, prereq: ["leng1"] },
  { id: "psico", ramo: "Psicología del Desarrollo y Aprendizaje en la Primera Infancia", semestre: 5, prereq: [] },
  { id: "musica", ramo: "Música", semestre: 5, prereq: [] },
  { id: "pracIng", ramo: "Práctica de Inglés", semestre: 5, prereq: ["fon2"] },
  { id: "pracI1", ramo: "Práctica Intensiva I", semestre: 6, prereq: ["eval"] },
  { id: "invest1", ramo: "Investigación Cualitativa y Cuantitativa", semestre: 6, prereq: ["eval"] },
  { id: "introInvest", ramo: "Introducción a la Metodología de la Investigación", semestre: 6, prereq: ["invest1"] },
  { id: "estudiosNino", ramo: "Aprendizaje del Inglés a través de Estudios de Desarrollo del Niño", semestre: 6, prereq: ["pracIng"] },
  { id: "cienciasNat", ramo: "Aprendizaje del Inglés a través de Ciencias Naturales", semestre: 6, prereq: ["pracIng"] },
  { id: "lingEsp", ramo: "Lingüística Española Aplicada", semestre: 7, prereq: [] },
  { id: "colab", ramo: "Creación de un Ambiente de Colaboración", semestre: 7, prereq: [] },
  { id: "curr", ramo: "Curriculum y el Desarrollo de la Educación Parvularia en Chile", semestre: 7, prereq: ["leng2"] },
  { id: "eventos2", ramo: "Aprendizaje del Inglés a través de Estudios de Eventos Mundiales II", semestre: 7, prereq: ["estudiosNino"] },
  { id: "b2", ramo: "Preparación y Rendición Examen Idioma Inglés MCER B2", semestre: 8, prereq: ["pracIng", "eventos2"] },
  { id: "inclusion", ramo: "Inclusión en Educación Parvularia", semestre: 8, prereq: ["curr"] },
  { id: "globales", ramo: "Aprendizaje del Inglés a través de Temas Globales en Educación", semestre: 8, prereq: ["eventos2"] },
  { id: "visuales", ramo: "Artes Visuales", semestre: 8, prereq: [] },
  { id: "pracI2", ramo: "Práctica Intensiva II", semestre: 8, prereq: ["pracI1"] },
  { id: "rolFam", ramo: "Educación Parvularia: El Rol del Educador y la Familia", semestre: 9, prereq: [] },
  { id: "invest2", ramo: "Práctica de Investigación – Acción", semestre: 9, prereq: ["introInvest"] },
  { id: "gestion", ramo: "
